{% set name = "nionui" %}
{% set version = "0.3.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0ce64e46701f00886d7626629c3bf83217803f7559d79cd39a05f7bac834d552

build:
  number: 0
  noarch: python
  entry_points:
    - nionui=nion.ui.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imageio
    - nionutils >=0.3.19
    - numpy
    - python >=3.6
    - pyqt

test:
  imports:
    - nion.ui
    - nion.ui.test

about:
  home: https://github.com/nion-software/nionui
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion UI framework.
  dev_url: https://github.com/nion-software/nionui

extra:
  recipe-maintainers:
    - cmeyer
    - ericpre
